import Head from "next/head";
import Homepage from "../components/homepage";
import Navbar from "../components/navbar";
import Login from "../components/login";

export default function Home() {
	return (
		<div>
			<Head>
				<title>GameThuk</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<Navbar />
			<Homepage />
			<Login />


			
		</div>
	);
}
