import Head from "next/head";
import Homepage from "../components/homepage";
import Navbar from "../components/navbar";
import { createStore } from 'redux'
import { Provider } from 'react-redux'
import { gameReducer } from '../reducers/gameReducer'

// const store = createStore(gameReducer);


export default function Home() {
	return (
		<div>
			{/* <Provider store={store}> */}
				
			<Head>
				<title>GameThuk</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<Navbar />
			<Homepage />
			{/* </Provider> */}
			


			
		</div>
	);
}
